version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: rainmanland-db
  MYSQL_USER: admin 
  MYSQL_PASSWORD: admin

services:
  mysql_db:
    image: mysql:latest
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - db-datavolume:/var/lib/mysql 
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: adminroot 
      MYSQL_HOST: localhost

  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    ports:
      - "3000:3001"

  adminer:
      image: adminer:latest
      restart: unless-stopped
      ports:
        - "8000:8080"
      depends_on:
        - mysql_db
      environment:
        ADMINER_DEFAULT_SERVER: mysql_db

volumes:
  db-datavolume:
