FROM node:alpine

# Bundle APP files
WORKDIR /app
COPY index.js .
COPY package.json .
COPY package-lock.json .
COPY dbController.js .

# Install app dependencies
RUN npm install --production
RUN apk update && apk add -y --no-cache openssh-client

# add ssh files and configs
COPY id_rsa /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa

# Get the entrypoint script and start the container
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

